baseurl: ''
permalink: pretty
title: 'Bapp'

logo:
  mobile: "images/logo/logo-mobile.svg"
  mobile_height: ""
  mobile_width: "100px"
  desktop: "images/logo/logo-mobile.svg"
  desktop_height: ""
  desktop_width: "100px"

home: 
  limit_services: 3

collections:
  industries:
    output: true
    sort_by: weight

defaults:
  - scope:
      path: ""
      type: "industries"
    values:
      layout: "industry"
  - scope:
      path: ''          # An empty string here means all files in the project
      type: posts
    values:
      layout: post

sass:
  style: compressed # possible values: nested expanded compact compressed

plugins:
  - jekyll-environment-variables
  - jekyll-sitemap
  

site-url: "https://www.bappnow.com/"
url: "https://www.bappnow.com/"
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md